[package]
name = "PiLights"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_ws281x = "0.4.2"
rand = "0.8.4"
hsl = "0.1.1"